/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SepoliaConfidentialLendingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BORROW_RATE"
      | "FIXED_INTEREST_RATE"
      | "INITIAL_RATE"
      | "asset"
      | "borrow"
      | "currentRate"
      | "emergencyWithdraw"
      | "getCurrentBorrowRate"
      | "getCurrentInterestRate"
      | "getEncryptedBorrowed"
      | "getEncryptedShares"
      | "getEncryptedTotalAssets"
      | "getEncryptedTotalBorrowed"
      | "getEncryptedTotalShares"
      | "lastUpdateTime"
      | "onConfidentialTransferReceived"
      | "owner"
      | "renounceOwnership"
      | "repay"
      | "supply"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialBorrow"
      | "ConfidentialRepay"
      | "ConfidentialSupply"
      | "ConfidentialWithdraw"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BORROW_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FIXED_INTEREST_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentBorrowRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentInterestRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBorrowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalBorrowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdateTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onConfidentialTransferReceived",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BORROW_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FIXED_INTEREST_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalBorrowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onConfidentialTransferReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ConfidentialBorrowEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialRepayEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialSupplyEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialWithdrawEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SepoliaConfidentialLendingVault extends BaseContract {
  connect(runner?: ContractRunner | null): SepoliaConfidentialLendingVault;
  waitForDeployment(): Promise<this>;

  interface: SepoliaConfidentialLendingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BORROW_RATE: TypedContractMethod<[], [bigint], "view">;

  FIXED_INTEREST_RATE: TypedContractMethod<[], [bigint], "view">;

  INITIAL_RATE: TypedContractMethod<[], [bigint], "view">;

  asset: TypedContractMethod<[], [string], "view">;

  borrow: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  currentRate: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentBorrowRate: TypedContractMethod<[], [bigint], "view">;

  getCurrentInterestRate: TypedContractMethod<[], [bigint], "view">;

  getEncryptedBorrowed: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedShares: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalAssets: TypedContractMethod<[], [string], "view">;

  getEncryptedTotalBorrowed: TypedContractMethod<[], [string], "view">;

  getEncryptedTotalShares: TypedContractMethod<[], [string], "view">;

  lastUpdateTime: TypedContractMethod<[], [bigint], "view">;

  onConfidentialTransferReceived: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      amount: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repay: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  supply: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BORROW_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FIXED_INTEREST_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentBorrowRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentInterestRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBorrowed"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedShares"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalAssets"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalBorrowed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalShares"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastUpdateTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onConfidentialTransferReceived"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      amount: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConfidentialBorrow"
  ): TypedContractEvent<
    ConfidentialBorrowEvent.InputTuple,
    ConfidentialBorrowEvent.OutputTuple,
    ConfidentialBorrowEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialRepay"
  ): TypedContractEvent<
    ConfidentialRepayEvent.InputTuple,
    ConfidentialRepayEvent.OutputTuple,
    ConfidentialRepayEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialSupply"
  ): TypedContractEvent<
    ConfidentialSupplyEvent.InputTuple,
    ConfidentialSupplyEvent.OutputTuple,
    ConfidentialSupplyEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialWithdraw"
  ): TypedContractEvent<
    ConfidentialWithdrawEvent.InputTuple,
    ConfidentialWithdrawEvent.OutputTuple,
    ConfidentialWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ConfidentialBorrow(address)": TypedContractEvent<
      ConfidentialBorrowEvent.InputTuple,
      ConfidentialBorrowEvent.OutputTuple,
      ConfidentialBorrowEvent.OutputObject
    >;
    ConfidentialBorrow: TypedContractEvent<
      ConfidentialBorrowEvent.InputTuple,
      ConfidentialBorrowEvent.OutputTuple,
      ConfidentialBorrowEvent.OutputObject
    >;

    "ConfidentialRepay(address)": TypedContractEvent<
      ConfidentialRepayEvent.InputTuple,
      ConfidentialRepayEvent.OutputTuple,
      ConfidentialRepayEvent.OutputObject
    >;
    ConfidentialRepay: TypedContractEvent<
      ConfidentialRepayEvent.InputTuple,
      ConfidentialRepayEvent.OutputTuple,
      ConfidentialRepayEvent.OutputObject
    >;

    "ConfidentialSupply(address)": TypedContractEvent<
      ConfidentialSupplyEvent.InputTuple,
      ConfidentialSupplyEvent.OutputTuple,
      ConfidentialSupplyEvent.OutputObject
    >;
    ConfidentialSupply: TypedContractEvent<
      ConfidentialSupplyEvent.InputTuple,
      ConfidentialSupplyEvent.OutputTuple,
      ConfidentialSupplyEvent.OutputObject
    >;

    "ConfidentialWithdraw(address)": TypedContractEvent<
      ConfidentialWithdrawEvent.InputTuple,
      ConfidentialWithdrawEvent.OutputTuple,
      ConfidentialWithdrawEvent.OutputObject
    >;
    ConfidentialWithdraw: TypedContractEvent<
      ConfidentialWithdrawEvent.InputTuple,
      ConfidentialWithdrawEvent.OutputTuple,
      ConfidentialWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
